// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class DefaultSortingTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void defaultSorting() {
    driver.Navigate().GoToUrl("https://geocitizen.herokuapp.com/");
    driver.Manage().Window.Size = new System.Drawing.Size(730, 945);
    driver.FindElement(By.CssSelector(".md-toolbar-section-end > .md-button .md-button-content")).Click();
    driver.FindElement(By.Id("a-login")).SendKeys("Manager");
    driver.FindElement(By.Id("a-password")).SendKeys("Manager_1");
    driver.FindElement(By.Id("a-login")).Click();
    driver.FindElement(By.Id("a-password")).Click();
    driver.FindElement(By.CssSelector("#authorization .md-button:nth-child(2) .md-button-content")).Click();
    {
      var element = driver.FindElement(By.CssSelector(".md-card-actions:nth-child(3) > .md-raised .md-button-content"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    Assert.That(driver.SwitchTo().Alert().Text, Is.EqualTo("Geolocation is turned off for this page"));
    driver.FindElement(By.CssSelector(".md-menu:nth-child(1) .md-button-content")).Click();
    driver.FindElement(By.CssSelector(".md-list-item:nth-child(2) > .md-list-item-router > .md-list-item-content")).Click();
    {
      var element = driver.FindElement(By.CssSelector(".md-list-item:nth-child(3) .md-list-item-content"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    driver.FindElement(By.CssSelector(".md-list-item:nth-child(3) .md-list-item-content")).Click();
    {
      var element = driver.FindElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element, 0, 0).Perform();
    }
    driver.FindElement(By.CssSelector(".md-table-head:nth-child(1) .md-table-head-label")).Click();
    driver.FindElement(By.CssSelector(".md-sorted .md-table-head-label")).Click();
    {
      var element = driver.FindElement(By.CssSelector(".md-menu:nth-child(2) .md-button-content"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    driver.FindElement(By.CssSelector(".md-menu:nth-child(2) .md-button-content")).Click();
    {
      var element = driver.FindElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element, 0, 0).Perform();
    }
    driver.FindElement(By.CssSelector(".md-list .md-list-item-button > .md-list-item-content")).Click();
    Assert.That(driver.SwitchTo().Alert().Text, Is.EqualTo("Geolocation is turned off for this page"));
    driver.Close();
  }
}
